### ISSUE TITLE
[Epic] Blog post case studies

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1014]
## Ideas
- [x] [2021 recap](https://foundation.mozilla.org/en/blog/design-in-a-movement-building-organization-reflections-from-2021/) @kristinashu 
- [x] [PNI visuals](https://foundation.mozilla.org/en/blog/the-design-process-behind-privacy-not-included-mental-health-apps/) (nancy) 
- [x] [YouTube](https://foundation.mozilla.org/en/blog/bringing-research-to-life/) (nancy & becca 
- [ ] PNI (nancy & becca up next)
- [ ] Blog page improvements @nancyt1 
- [ ] Report page improvements @beccaklam 
- [ ] Design system progress @sabrinang
- [ ] New email templates
- [ ] PNI
- [ ] Common Voice

Other ideas
- Collaborating with devs
- Brand guideline
- Working open
- UX/UI progress

Goal and audience
- The primary goal is to elevate the design team's work and educate staff on what we do. Secondary would be designers at other orgs who tackle similar problems as us.

**Comment by kristinashu** [comment]
@nancyt1 curious if you have any suggests on what [tag](https://redpen.io/yxc54f2b2d1dc3b782) to use for these?
