### ISSUE TITLE
Print ad

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1061]
Print date is July 20th. The deadline to reserve is July 15th 2pm PDT, with *creative due Tuesday July 19 at 9am PDT*.

[Related to this blog post.](https://blog.mozilla.org/mozilla/calling-for-antitrust-reform/)

[Same template as in the passed](https://drive.google.com/drive/folders/1A1uXYVh8uQaZLQWG_3m2BfHY6bl8pfDS) https://github.com/mozilla/foundation.mozilla.org/issues/5333

I've copied the files into [this Drive folder.](https://drive.google.com/drive/folders/1Ji6K0oC6iLD_OjDB3HF2FdpNWrTKOp-4)

[Project brief & timeline.](https://docs.google.com/document/d/1xLZLsaMOnuBRKYlZO2yU9wUteiAJcXdvxqW9lnKx4jA/edit#heading=h.w25jmdycdpd7)

### Todo
- [x] Confirm with Lindsay that the specs are the same: 12" wide x 21" high in PDF format
- [x] Anil to share [draft letter copy](https://docs.google.com/document/d/1VEaeWtRjiOtLc0idwAxBNx9kgygIR-ErMZTQLaISG5Q/edit)
- [x] Kristina to mock-up the text
- [x] Get approval from Mark on mock-up
- [x] On Monday, get list of signatures
- [x] Kristina to update names on ad
- [x] @sabrinang  to do final review (most likely on Monday)

**Comment by kristinashu** [comment]
The copy for the letter has been approved so I've updated the file https://redpen.io/dk173ab0d5455b0fa1

### Todo
- [ ] Share in the project slack channel for feedback
- [ ] Update signature names once we have them
- [ ] Update the 6,000+ once we have the number
- [ ] Work with moco to redirect the url

@sabrinang not sure how much design feedback is needed right now but if you have any then please let me know!

**Comment by kristinashu** [comment]
@sabrinang this is ready for your review!

I've updated the names based on [this list](https://docs.google.com/spreadsheets/d/1p3LcXnFURt_F7ACiKkDBhhuErYMcWfYWNWWeUUAYbU0/edit?usp=sharing) (the names were already cleaned up).

I've [packaged both the black/white version and a color version](https://drive.google.com/drive/folders/1K6udAilrOsifBtc8eiFQODmX2AVAOD3R), although all that we will be sending is the PDF. It's up to us which one we want to use. Do you have any preferences?

**Comment by kristinashu** [comment]
via Anil
> apologies, I noticed some "?" in the ad, and I found 5 "broken" names in the list I send you - I have put them at the top of the list now. Sorry about that. I still like the colour version - but unsure of how the names will show up in print - wouldn't want them to look too faded. 

So I will update those names later.

**Comment by kristinashu** [comment]
Removed the "?" and references of "none".

Ready for review, for real!

**Comment by sabrinang** [comment]
Overall looking good and name background looks balanced. 

Small things to consider:
- format in last area, is there suppose to be space between Sincerely, and Mozilla
- if we are using color blue, perhaps make the mozilla.org/openletter link blue for it to stand out

**Comment by kristinashu** [comment]
Thank you for the suggestions! I've [updated the design](https://drive.google.com/file/d/1MA7kQ_-OLLHmfzKu3SYsn5ftDTtI9xXH/view) and shared it with stakeholders for final review.
