### ISSUE TITLE
[PNI reproductive health apps] Thumbnails for site

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1063]
### Todo
- [x] Get [list of apps](https://docs.google.com/document/d/1B6BDwQJ8d6UxYHW-4sPx1OziTWQtCrDz6e9HNJkchrM/edit)
- [x] Create a thumbnail for each
- [ ] @nancyt1 to do a design review of them
- [x] Share link to images in slack channel

**Comment by kristinashu** [comment]
[I've started this in Figma](https://www.figma.com/file/37oqkJjSCf6fhAJWGhAWbE/PNI-Product-Images-2022?node-id=0%3A1) and [Drive](https://drive.google.com/drive/folders/1NUagHQA93bMQi1cxS-Bwq9M-FPXwrbpD).

**Comment by kristinashu** [comment]
[They're all done! ](https://drive.google.com/drive/folders/1KYUPJfoN6pAOl5gdW7JNCPo4yEOk-vvu)Nancy please review them when you have a chance. I made them look like app icons, hope that is ok. The wearable were tricky so let me know if you have any other ideas for those.

**Comment by nancyt1** [comment]
All looks good to me! Love how the wearables look!
