### ISSUE TITLE
[PNI reproductive health apps] Produce all marketing assets

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1066]
Based on [PNI reproductive health apps] Creative direction #1065 &  [PNI reproductive health apps] Gather list of assets #1064 https://docs.google.com/spreadsheets/d/1erw_8gVTv_KM-3TcW8VYBa1wK8I1osMFt-YJTAo6MwQ/edit#gid=0

[Social Media Copy Doc](https://docs.google.com/document/d/1xmOaUly82L0PDrvSW0BaZ4eemBaW64CIpcBgxq5_W9k/edit)

### Todo
- [x] Create all assets listed
- [x] Share for feedback from stakeholders
- [x] Share link to folder in slack

**Comment by nancyt1** [comment]
Graphics have all been uploaded to the [drive](https://drive.google.com/drive/folders/1JTfnMt6d-5mWoLsIeuL59B9P6Xn2EakX) and I've shared the link in the slack.
