### ISSUE TITLE
[YouTube] Marketing assets epic

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1086]
- [ ] Gather [list of assets](https://docs.google.com/spreadsheets/d/1uWo3JmBDPxNpNZWAQ2p6SU2hBCzM1oGGYFuB85mZ5xc/edit?usp=sharing)
- [ ] Review list of assets
- [ ] Open tickets to create individual assets
