### ISSUE TITLE
Graphics for research hub

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1091]
Kasia has been populating https://foundation.mozilla.org/research but has flagged that she needs some graphics. 

### Todo
- [x] Check in with Kasia in #mofo-project-research-hub
- [x] Create a default graphic for reports doesn't have one
- [x] Fix/crop existing graphics if needed
- [x] Add images for team authors (e.g. Insights and Advocacy
- [x] Create a Research Hub banner for the front page

**Comment by kristinashu** [comment]
Done https://foundation.mozilla.org/research
