### ISSUE TITLE
[PNI] Product images for holiday edition

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1095]
### Todo
- [x] Get list of products ([list](https://docs.google.com/document/d/1WfXmK7NNdVoKSJQqHOh1LQ03rWIwufLcZQXrDYdgGCc/edit)) ([sheet](https://docs.google.com/spreadsheets/d/1Sk9vy8LFBRZqUQXIWxTKVpIplbFA-41FPRYe1mj8INQ/edit#gid=273266428))
- [x] See which ones need a new image
    - [x] Amazon Echo Studio
    - [x] Amazon Halo Rise
    - [x] Lenovo Smart Clock
    - [x] Amazon Astro Robot
    - [x] MyQ Garage by Chamberlain
    - [x] Steam Deck (Valve)
    - [x] Amazon Voice Remotes
    - [x] Tivo Stream
    - [x] Xfinity Flex
    - [x] Nook
    - [x] Google Pixel Watch
    - [x] Garmin Fenix 
    - [x] Garmin Epix
    - [x] Meta Quest Pro 
    - [x] Huawei Watch Kids 4 Pro
    - [x] TickTalk 4 (smart watch for kids)
    - [x] Spacetalk Adventure (smart watch for kids) 
    - [x] Verizon GizmoWatch (smart watch for kids) 
    - [x] Autel Evo Lite+
    -------
    _Check to see if these have images_
    - [x] Lenovo Smart Display
    - [x] Logitech Circle
    - [x] Logitech Circle Video Doorbell
    - [x] Ezviz Video Doorbell 
    - [x] Honeywell WiFi Smart Thermostat
    - [x] Dyson 360 Heurist
    - [x] Shark Robot Vacuums 
    - [x] Bissell' Robot Vacuums
    - [x] Roborock Robot Vacuums
    - [x] Neato Robot Vacuums
    - [x] Samsung JetBot AI 
    - [x] Lenovo Tablets
    - [x] Huawei MatePad Tablets
    - [x] Orbit Trackers
    - [x] Cube Shadow
    - [x] Innway Card
    - [x] Nutale Nut3
    - [x] Osmo Genius
    - [x] Merge Cube
    - [x] EMAX Tinyhawk
    - [x] RUKO Drones
    - [x] Holy Stone Drones
    ---------
     _Research not done for holiday_
    - [x] U by Moen - cloud-based showering system, Alexa-connected
    - [x] Moen’s smart faucet
    - [x] Kohler DTV+ with KOHLER Konnect
    - [ ] Kohler smart bathtub
    - [x] Kohler [Smart Toilet](https://www.smarthome.kohler.com/toilets-and-seats) 
    - [x] Philips Hue - smart lights
    - [x] Wyze Bulb
    - [x] Ring Smart Lighting
    - [x] Nanoleaf
    - [x] Wemo Thread Smart Plug
    - [x] Ring Outdoor Smart Plug
    - [x] Amazon Smart Plug
    - [x] Wyze plug
    - [x] Aventon Level.2/ Aventon Pace/Aventon Aventure ebikes 
    - [x] VanMoof Bike (built-in GPS, European)
    - [x] Rad Power RadRover/RadMission/RadRunner
    - [x] Lectric eBikes 
    - [x] GoCycle Ebikes G4/G4i/G4i+ 
    - [x] Woom Up 5 & 6 (ebike targeted at kids with the Fauza Rider app)

- [x] Gather the images
- [x] Crop the images
- [x] Share with Jen

**Comment by nancyt1** [comment]
Images for new products that are releasing for the holiday guide are in the [drive](https://drive.google.com/drive/folders/1R-bmrlUm-OmAi8jHUQwX_pjlETLk4UKW) as well as images that Jen marked for release after the holiday launch. I also moved images we already had but didn't publish last year into the 2022 folder. There's one product that I'm asking Jen for clarification on but it won't be in the holiday launch anyway. 
Tagging Jen for review now!

**Comment by nancyt1** [comment]
Shared with Jen and she said not to worry about that one image. Done!
