### ISSUE TITLE
Update our /brand pages

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1127]
Our /brand pages are out of date. We should update them so they are more useful to us, other staff, and contractors.

## Todo
- [x] Brainstorm on IA [(Figjam with the team)](https://www.figma.com/file/t8rWjvPG7Lfgkr3MkS8wiy/Documentation-IA?node-id=0%3A1&t=K78hOKDIFAQpz77i-1)
- [x] Recreate pages under[ /design](https://foundation.mozilla.org/en/docs/design/)
- [x] Identify section owners (marketing owns: Marketing Graphics, Photography, Video & Motion)
- [x] Progressively update the content (need individual tickets)
- [x] Delete and redirect /brand pages
- [x] Share with staff
