### ISSUE TITLE
Petition workshop

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1239]
via Shing:

> Workshop Goal: The goal of this workshop is to get aligned cross-functionally on what the ideal flow looks like from both a user perspective and a backend engagement perspective to help us reach our goals. Once we have this mapped, we (tech platforms) will take this back and scope what the changes are in design, dev, and on the back end to be able to share back a timeline with the engagement team.

> **Agenda:**
> - Goals - what are the short term and long term goals for petitions? (For example, short term is to get a newsletter sign up and/or donation in the same day, long term is to take further action on the topic
> - User Personas - who is the user we are targeting with a Petition? Is it deeply engaged people? Are we trying to engage new people through petitions? Come to a shared agreement about who we are engaging.
> - Ideal State - Designing ideal state of how petitions will work. From design to reporting needs. 

> **Prework:**
> We want to provide folks with enough time to think about and come with ideas. We will target sending a workshop pre-work e-mail on Thursday, Sept 7 by midday.
> - Build out the miro board here so folks can take a look in advance: https://miro.com/app/board/uXjVMq8Ymk0=/?share_link_id=701611354681 (Workshop itself + Prework)
> - E-mail text: Set the stage, provide the agenda ([Text will be populated here](https://docs.google.com/document/d/1pzASh-JEYv8YVVf6NRVnHOKeFygtcLb4amzczNHh1ww/edit?usp=sharing))
> - Ask folks to go through and sign a petition on the website, familiarize self with existing user journey + review the data flows to understand where data goes today.

### Todos
- [x] Kick off with Shing
- [ ] Kristina to do first draft of miro board
- [ ] Design to review
- [ ] Review Prework listed above
- [ ] Attend workshop

**Comment by nancyt1** [comment]
I think this ticket is done!
