### ISSUE TITLE
Icons for RCC Playbook

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1252]
Design icons for https://foundation.mozilla.org/en/responsible-computing-challenge-playbook/ that can be used consistently across the Playbook. These will be used to differentiate types of content. The goal is to add more visual appeal and navigational cues for the Responsible Computing Challenge. 

Shannon's past RCC assets are [here](https://drive.google.com/drive/folders/1cm34MhHp0JaC4E_TY-QsHUD9R47wCtW7?usp=drive_link) and the brief from Joycelyn is [here](https://docs.google.com/forms/d/1W4i2Lou1Wcn4mryw80NvX_CV_n83KyGkPXLC3g9F9_E/edit#response=ACYDBNh-RYtY2-KytbsQLdZ6c5nt4t59m0Jt_pKlw8H1kZUYP6h1pqlwyBymAlPajWNSCOk) 

Joycelyn mentioned: There are various types of content in the Playbook and I thought it might be nice to have a visual marker to indicate that something is designated as "teaching material" (vs. articles). Right now, I just have a icon for a book (wrong size and doesn't match the site). Also, within articles, there are sections for "key questions", "checklists", "examples", "resources", and "related pages".  Perhaps a visual element for each? We can re-deploy some of the existing icons, but  need some additional ones'

**Todo's**
- [x] - Review the site and see where icons would be helpful
- [x] - Confirm with Joycelyn that these are the areas she had in mind
- [x] - Determine icon style (should align closely with the direction Shannon has already created) 
- [x] - Create all icons
- [x] Test within Wagtail
- [x] - Share export with with stakeholder and for her to upload them to the site
- [x] Gain final approval

Additional Scope Pieces:
- Logo [#11287](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11287)
- Social Media & Blog Assets

**Comment by tessheinricks** [comment]
Icons have been designed, tested, and exported. 

- Final [web optimized icons](https://drive.google.com/drive/folders/1s257U1XDn0F45LcVide3hUXAFIkFAzYW?usp=drive_link) - Supplied in a primary purple colorway as well as a grayscale and cyan + gold 
- [Additional icons](https://drive.google.com/drive/folders/1J6EmOlTO740w6C9mlZnTNA1WOCOJD6ih?usp=drive_link) for future use and accessible scaling needs 
- The [figma file](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?type=design&node-id=1405%3A13014&mode=design&t=y1muaRKY2MtsNbFO-1) where these assets reside

**Comment by tessheinricks** [comment]
Icons are now in use within the [Responsible Computing Challenge Playbook site](https://foundation.mozilla.org/en/responsible-computing-challenge-playbook/)
