### ISSUE TITLE
Layout for AI Funding Principles CMS page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1253]
Lindsey needs help designing a new page in our CMS.
[Notes doc](https://docs.google.com/document/d/1FpUYQEPu5UeSbQLKOg4vzXEbaW0CBEr1H0QdEaRbW9s/edit#heading=h.e6hawwj66q6e)

### Timeline
- Draft copy Oct 18 
- Final copy Oct 31
- Launch Nov 7

### Graphics
Shannon has meet with Lindsay and is ready to start on the graphics as soon as the principles are shared with her

### Todo's
- [x] Create a page under /what-we-fund (shouldn’t appear in sub nav)
- [x] Determine best page type (probably Article since Banner would show full sub nav) (Lindsey likes https://foundation.mozilla.org/en/research/library/is-that-even-legal/builders-guide/)
- [x] Add draft content and determine ideal layout and blocks
- [x] Use placeholder graphics then let Shannon know what graphics/dimensions are needed
- [ ] Share with stakeholder for feedback
- [ ] Stakeholder responsible for making copy updates
- [ ] Work with stakeholder to add a “call-out” (using an existing cms block) to https://foundation.mozilla.org/en/what-we-fund/ that links to the new page

**Comment by kristinashu** [comment]
Linking to feature request ticket https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11333

**Comment by nancyt1** [comment]
Created base [layout](https://foundation.mozilla.org/en/what-we-fund/trustworthy-ai-funding-principles/) with placeholder graphics. I'll touch base with Lindsey and Shannon to make sure everything's good to go before I close.

**Comment by nancyt1** [comment]
Opened another ticket to finish this work #1262
