### ISSUE TITLE
'In Transparency We Trust?' report CMS & PDF

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1280]
- Stakeholder: Ramy
- Launch date: Feb 26, 2024
- New Article page similar to https://foundation.mozilla.org/research/library/ai-transparency-in-practice/ai-transparency-in-practice/
- [Notes doc ](https://docs.google.com/document/d/1UENOfZLu-TEsmmQVotYdeN4_ALYV6N3QC4Jig4KPryE/edit)
- External illustrator is creating static hero image for the landing page & PDF
- Final deliverables: Single Article page type landing page, Research hub landing page, PDF (English only)
- Graphics are being created in https://github.com/MozillaFoundation/Design/issues/1288

## Waiting on
- [x] Approved [copy](https://docs.google.com/document/d/1Vq3qAgMUYgIvFPYJK38Lk0wjfGjp52nwSOq_YJE2KXY/edit)
- [x] Ramy to share final hero illustration and working files
- [x] Ramy to share photo of co-author 
- [ ] Decide on Call To Action (Ramy to check with Marcomms)  

## Todos
- [x] Create private project slack channel to coordinate (slack thread is working)
- [x] Add new author profile
- [x] Add content to an new Article page
- [x] Teach Ramy how to use add Footnotes 
- [x] Give feedback to illustrator and test hero image on page 
- [x] Edit/crop hero image for OG share image
- [x] Style and format the PDF doc
- [x] Replace all placeholder images
- [ ] Create mzl/la short link
- [x] Attach PDF to Article page

## Prelaunch
- [x] Remove password
- [x] Test OG image and meta description
- [x] Make sure Ramy adds to Research hub (creates landing page)

**Comment by nancyt1** [comment]
Report is live and launched!
