### ISSUE TITLE
'Trustworty AI Whitepaper 2.0' Report in CMS

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1289]
- Stakeholder: Lindsey
- Launch date: Feb 20, 2024
- New Article page similar 
- External agency will create the PDF and graphics for the PDF
- [Copy](https://docs.google.com/document/d/1OexQndYKNA3kg-d4NCn6Ap_HTJyh__KwK5ihT4QFg1I/edit)

## Todos
- [x] Set up landing page and article page https://foundation.mozilla.org/cms/pages/27298/edit/
- [x] Lindsey to add content
- [x] Create short link https://mzl.la/accelerating-trustworthy-AI
- [x] Get profile images and add new authors 
- [x] Style text where possible
- [x] Add PDF download [blocked]
- [x] Get illustration and working files from agency [blocked]
- [x] Add graphics once we have them [blocked]

## Prelaunch
- [x] Remove password
- [x] Test OG image and meta description
