### ISSUE TITLE
TikTok Reporter CMS landing page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1299]
Becca R will be launching this new reporter app April 16 (ideally the page will be ready by April 1).

An agency is building the app but it needs a home on our site.

via https://mozilla-hub.atlassian.net/browse/MOFOTP-143 "We are putting together a landing page for the TikTok Reporter project that will direct users to download the app (iOS and Android). This will include orientation information. This will likely also include a module where people can sign up for updates on the project."

Although similar to https://foundation.mozilla.org/en/youtube/regretsreporter/, this is more of a research project than an advocacy campaign. Becca does not think mofo will be doing other TikTok related work beyond the reporter and it's research reports.

## Waiting for Becca on
- [x] Reaching out to the illustrator Ramy used (she likes this example with mini people https://adriavolta.com/portfolio/litigation-departments/ as a node to the YouTube illustrations)
- [x] Draft copy (CTA is link to Apple and Android store)
- [x] Coordinating with engagement (should there be a newsletter signup on the page?)
- [x] Coordinating with marketing (will there be video?)

## Todo 
- [x] Explore a couple different layout options using existing CMS pages and blocks 
- [x] Things to consider: should there be screen shots or how to instructions? Any considerations since this is a mobile app?
- [x] Design review and file clean up
- [x] Confirm url foundation.mozilla.org/TikTokReporter

Follow up pre-launch ticket
- QA on staging and prod
- Add content, illustrations, meta info

**Comment by kristinashu** [comment]
I started to explore what a cms page type of this could be https://www.figma.com/file/zMGcZQtSI2kqp4pgRqrOlu/TikTok-Reporter-(app-landing-page-template)?type=design&node-id=0%3A1&mode=design&t=EdkYpKxuTOgNlnBK-1

Talked to devs about three approaches:
- Copy YouTube page and make another hard coded TikTok page
- Keep the top hard coded but make the bottom editable with blocks similar to the Banner page type
- Make the entire page editable 

Devs lean towards making it cms editable since content is bound to change between now and launch and beyond.

**Comment by kristinashu** [comment]
Share the initial mock-up with Becca. She says if there will be a video then it would be at the bottom of the page and she thinks the email sign up works well. She's happy with the general direction. I will share at design crit for more detailed feedback.

**Comment by kristinashu** [comment]
- Becca meet with the illustrator and they will be working on this. 
- I've confirmed with Michael/Christian that our regular newsletter sign up snippet will work for this
- Becca has shared some [draft copy](https://docs.google.com/document/d/1kpChkpP51I-ubjh5EILW7_QBJPtPLR05j2xwNb29RkY/edit#heading=h.6aalp8pdiyvs) and is getting input from Kevin and Jesse  

A designer will need to clean up the Figma file and do a thorough design review of the file and then this will be ready for dev. I feel the backend is ready and it's just the details of the front end styling that needs to be finalized (spacing, button size, etc). cc @simont-cr

**Comment by kristinashu** [comment]
@tessheinricks will do a design review and clean up of the Figma file!

**Comment by tessheinricks** [comment]
Hi @kristinashu  and team! I've completed my review & file tidy. You can find the Ready for Dev design files [here](https://www.figma.com/file/zMGcZQtSI2kqp4pgRqrOlu/TikTok-Reporter-(app-landing-page-template)?type=design&node-id=64%3A13207&mode=design&t=sxwD0ThhBCQVaKAA-1) within Figma.

Kristina, you'll notice I defaulted to the current button height: 41. When cleaning up I found the larger buttons competed too much with the headline and ultimately felt unbalanced. However, I did take the time to produce a version with a larger button (height: 46) which you can view [here](https://www.figma.com/file/zMGcZQtSI2kqp4pgRqrOlu/TikTok-Reporter-(app-landing-page-template)?type=design&node-id=64%3A15519&mode=design&t=sxwD0ThhBCQVaKAA-1) within the design explorations. You'll notice I played around with the mobile composition for future revisions (looking at content order and introducing center alignment + full width buttons to align with mobile best practices & experience cohesion). 

I took the time to expand the design system to encompass the [new icons](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?type=design&node-id=607%3A8128&mode=design&t=MqwUIzEAargVvFrx-1) along with an additional [link button stack](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?type=design&node-id=4334%3A15900&mode=design&t=MqwUIzEAargVvFrx-1). 

Please take a look and let me know if you have any questions. Thanks all!

CC: @simont-cr

**Comment by kristinashu** [comment]
Amazing, thank you so much for cleaning this up Tess!
