### ISSUE TITLE
Write Design QA rubric / checklist

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#15]
Discussed this with Ricardo. He is going to create a checklist by Friday, which we will be able to document in issue #8 .

I know @iamjessklein had the start of this at one point but we were unable to dig it out from the depths of Github...

**Comment by iamjessklein** [comment]
Sounds good.  @vazquez  [This blogpost on Design QA might be helpful](http://jessicaklein.blogspot.com/2015/01/quality-assurance-reviews-for-design_27.html) - I wrote it after we did the QA a few heartbeats back.

**Comment by vazquez** [comment]
#### UI QA Checklist

###### Cross-Browser
- Displays & functions correctly in IE10
- Displays & functions correctly in Firefox (latest 2)
- Displays & functions correctly in Chrome (latest 2)
- Displays & functions correctly in Safari (7+)
- Displays & functions correctly on Mobile Safari (7+)
- Displays & functions correctly on Mobile Chrome (latest)
- Displays & functions correctly on Mobile Firefox (latest)

###### Content and Typography
- The use of H1, H2, and H3 headings is appropriate
- There are no outlier fonts
- All screen prompts are specified in the correct screen font
- All text is properly aligned
- All text free from spelling and punctuation errors
- Content has been placed consistently
- Content is marked-up semantically
- List styles are consistent
- There are no broken links
- Line height is appropriate
- Letter-spacing is appropriate
- Ensure all the content for respective words to be in lower and upper case
- Copy is clear, concise, and meaningful

###### Images
- Are all graphics properly aligned?
- Are graphics being used the most efficient use of file size?
- Are graphics optimized for quick downloads?
- Does text wrap properly around pictures/graphics?
- Is it visually consistent even without graphics?
- Images have appropriate alt text
- SVG assets are being used where possible
- Favicon has been created and displays correctly

###### Forms and Instructions
- Are all error messages text spelt correctly?
- Are all micro-help text (i.e tooltip) spelt correctly?
- Do forms have placeholder information?
- Do forms have success states?
-  Are labels properly aligned?
-  Form elements span full width when in mobile layouts

###### Other UI Elements
- Buttons contain border-radius
- Buttons contain box-shadow
- Buttons contain inset box-shadow
- Button text is properly aligned
- Buttons have a hover state 
- Buttons have an active state
- Links have a hover state

**Comment by cassiemc** [comment]
Rewriting / ordering a bit of what Ricardo did above and adding checklist boxes so this can become a functional list in our process. 

However, I suspect content here needs an update. @vazquez could you take a pass on this list to make it more accessible for all projects? So when you and @lovegushwa look at the brand elements template, you might revisit "other UI elements" as it pertains to Teach, Webmaker, Advocacy, etc.

#### UI QA Checklist

###### Cross-Browser
- [ ] Displays & functions correctly in IE10
- [ ] Displays & functions correctly in Firefox (latest 2)
- [ ] Displays & functions correctly in Chrome (latest 2)
- [ ] Displays & functions correctly in Safari (7+)
- [ ] Displays & functions correctly on Mobile Safari (7+)
- [ ] Displays & functions correctly on Mobile Chrome (latest)
- [ ] Displays & functions correctly on Mobile Firefox (latest)

###### Content and Typography
- [ ] The use of H1, H2, and H3 headings is appropriate
- [ ] There are no outlier fonts
- [ ] All screen prompts are specified in the correct screen font
- [ ] All text is properly aligned
- [ ] All text free from spelling and punctuation errors
- [ ] Content has been placed consistently
- [ ] Content is marked-up semantically
- [ ] List styles are consistent
- [ ] There are no broken links
- [ ] Line height is appropriate
- [ ] Letter-spacing is appropriate
- [ ] Ensure all the content for respective words to be in lower and upper case
- [ ] Copy is clear, concise, and meaningful

###### Images
- [ ] All graphics properly align
- [ ] Graphics being used are optimized for file size
- [ ] Graphics are optimized for quick downloads
- [ ] Text wraps properly around pictures/graphics
- [ ] Visually consistent even without graphics
- [ ] Images have appropriate alt text
- [ ] SVG assets are being used where possible
- [ ] Favicon has been created and displays correctly

###### Forms and Instructions
- [ ] All error messages text spelled correctly
- [ ] All micro-help text (i.e tooltip) is spelled correctly
- [ ] Do forms have placeholder information?
- [ ] Forms have success states
- [ ] Labels properly align
- [ ] Form elements span full width when in mobile layouts

###### Other UI Elements
- [ ] Buttons contain border-radius
- [ ] Buttons contain box-shadow
- [ ] Buttons contain inset box-shadow
- [ ] Button text is properly aligned
- [ ] Buttons have a hover state 
- [ ] Buttons have an active state
- [ ] Links have a hover state

**Comment by vazquez** [comment]
I updated the comment above. I'm comfortable with closing this issue and filing new issues as needed to modify and update this list.

:boom:
