### ISSUE TITLE
[Hawaii All-Hands 2016] Information Architecture Proposals

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#215]
We will create a variety of IA charts to help illustrate the complexity and challenges with different approaches and perspectives. This visual will be used to guide the discussion topic at Hawaii.

If we have time, we can plan a session around IA - if not, we will find another way to seek feedback (digitally or we can post it up on the wall throughout the week) .   

#### Tasks before All-Hands:
- [ ] after "fuel the movement" program review, gain clarity on content and ask follow up questions 
- [ ] post initial ideas for feedback 
- [ ] refine charts to be presented at all-hands
- [ ] plan questions or prepare session *(if we have the time to make it a session)*

cc: @hannahkane @xmatthewx @taisdesouzalessa @kristinashu @flukeout @simonwex @chrislarry33

**Comment by hannahkane** [comment]
To further clarify, when we say "illustrate the challenges with different approaches," I think one of the main questions we're looking to discuss is "Should we do this in an iterative way, or should we take the time to carefully research and develop a comprehensive solution?" If we can use draft IA charts to inform a conversation about which approach is better, I'd consider this a success.

In other words, the outcome of this is likely not about the specifics of the IAs we come up with, but rather clarity about *how* we will approach this project moving forward.
