### ISSUE TITLE
Epic: Create our master visual library template

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#373]
**Deadline July 19**

## Goals
1. Have a cohesive mofo brand look & feel
2. Make it quick & easy to create beautiful graphics that are on brand

## How
Collaboratively create one illustrator file full of our best design elements that are easy and effective to use.

Sabrina create [something like this](https://drive.google.com/file/d/1orb066KvQ8y2SYWiDy6GH2KPHXkyHXoi/view) for mozfest last year (see screen cap below).

### Finish audit of your recent work
Week of June 10 - add to Sabrina's [deck](https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit?usp=sharing)
- [x] Sabrina
- [x] Natalie
- [x] Rebecca
- [x] Kristina

### Make one slide highlighting your favorite Mozilla work
Week of June 10 - add to Sabrina's [deck](https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit?usp=sharing)
- [x] Sabrina
- [x] Natalie
- [x] Rebecca
- [x] Kristina

### Make one slide highlighting your aspirational benchmarks
Week of June 10 - add to Sabrina's [deck](https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit?usp=sharing)
- [x] Sabrina
- [x] Natalie
- [x] Rebecca
- [x] Kristina

### Compile 
Week of June 24 - add to Sabrina's [deck](https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit?usp=sharing)
- [x] Create moodboard of elements we want to keep (illustrations, photo treatment, textures/patterns)
- [x] Define use cases (social, blog, email, site banners, site illustrations, for both illustrations and photos)
- [x] Define when it is ok to make exceptions

### Create template
Week of July 1 - new Illustrator file
- [ ] Create an illustrator file with all final patterns, textures, colors, gradients, effects...
- [ ] Add in work from - Illustration/ templates for brand #365
- [ ] Add file to [wagtail page](https://foundation.mozilla.org/en/docs/brand/design/)

**Mozfest template benchmark**
<img width="678" alt="image" src="https://user-images.githubusercontent.com/1068783/59136397-d3bb8800-8937-11e9-8fb2-8f0fdf7b2653.png">

cc: @xmatthewx

**Comment by sabrinang** [comment]
linking to MozFest 2018 style guide slides for reference as @natalieworth mentioned it was a useful overview: https://docs.google.com/presentation/d/1Otj7kAwG3EyQd_Ya1K7jigJ0YLRMMiCbuq_L4QCbM1M/edit#slide=id.g1ea5ab4fd9_0_139

**Comment by kristinashu** [comment]
Some suggested next steps but please ping me if you want to do something differently (please open tickets if needed):

- [ ] Create new foundational illustration style for /initiative, /participate, and new donate page [@natalieworth]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/1068783/60550861-3bb68180-9cde-11e9-9b23-c1b50d48f3b7.png">

- [ ] Reduce number of black/white textures we use and gather them to a master file [@natalieworth]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/1068783/60550959-8b954880-9cde-11e9-8a3d-9db843de07f8.png">

- [ ] Make this reusable and add it to the master file  [@natalieworth]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1068783/60550987-ac5d9e00-9cde-11e9-99f6-d69c753e6504.png">

- [ ] Reduce our number of textures/shadows/cutouts and add to master file with a few examples [@beccaklam]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/1068783/60551280-acaa6900-9cdf-11e9-88ad-59ad61cf4097.png">

- [ ] Gather textures/treatments to use to create a master file for mozfest contract designer [@sabrinang]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/1068783/60551383-06129800-9ce0-11e9-920b-e3e6b2c04c29.png">
<img width="651" alt="image" src="https://user-images.githubusercontent.com/1068783/60551397-1296f080-9ce0-11e9-8cd3-66a54030eb6e.png">

- [ ] Compile and organize master file and folder [@kristinashu]

**Comment by natalieworth** [comment]
Created and added to t[he Foundation Brand deck here](https://docs.google.com/presentation/d/1oMRxQ2NZiebhMnwGkDJQPC6-iD8xYqBeopJhO3uEBT4/edit#slide=id.g1ea5ab4fd9_0_139).

**Comment by kristinashu** [comment]
@sabrinang @natalieworth I believe these are the final step for considering this work done. I've create separate tickets and will close this master one. Please update the tickets or open a new one if I've missed anything! 
- Make All Hands slide style reusable and add it to the master file - https://github.com/MozillaFoundation/Design/issues/384
- Adapt MozFest style guide to work for general MoFo - #387
- Minimal documentation in [Brand deck here](https://docs.google.com/presentation/d/1oMRxQ2NZiebhMnwGkDJQPC6-iD8xYqBeopJhO3uEBT4/edit#slide=id.g1ea5ab4fd9_0_139)  - #388
- Add file and screen caps to [wagtail page](https://foundation.mozilla.org/en/docs/brand/design/)  - #388
- Compile and organize master file and [folder](https://drive.google.com/drive/folders/1FsYaAToeHrueI4kQvqYwNHSnm8idrgh1?usp=sharing) - #388

Note for this sprint: it sounds like YouTube might become a higher priority, if that's the case then this work might get pushed back to next sprint.
