### ISSUE TITLE
[Personas] Master ticket - Personas 2019/2020

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#434]
### Background:
With our new focus on audience, the past created Personas will need to be reviewed and we will also need to build a new set. This master ticket highlights all the necessary steps in oder to make it happen.

### Project's phases:
**1. Phase 1: exploration - what we have done in the past, what is the vision for our audience**
- [x] Past Personas: where we left things off #435
- [x] Connect with Anil on vision of the future + conversations that have already happened 
- [ ] Build an Action Plan

**2. Phase 2: new set and old set - create a new set and integrate with old set (if still relevant)**
_This step will depend on what happens in Phase 1 - it will be updated once Phase 1 is clearer_
- [ ] Accessibility considerations: how to include accessibility in our Personas set? @youriwims and @alanmoo  as though partners on that

 **3. Phase 3: adoption and usage - how we can motivate staff to use personas and also to make them accessible to all**
- [ ] Interview staff about their current processes on audience consideration and shared understating within their team. 
- [ ] Accessibility and Usage of Personas #433

cc: @kristinashu @beccaklam

**Comment by taisdesouzalessa** [comment]
I am closing this ticket for now due to our focus on Audiences at the moment: #446. I may reopen it in the future as we move things more into a Personas direction.
