### ISSUE TITLE
Microtargeting explainer

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#437]
### Goal 
Help the Mozilla audience understand what we mean by political ad microtargeting.

### Phase 1: Blog post
Design a few graphics for an explainer blog post. 
- [Copy doc](https://docs.google.com/document/d/1iexHYBcw4fNJcyQYaSnfTzVLEBku38hC-k0lJsaedPM/edit?ts=5ddd6790)
- [Stakeholder interview](https://docs.google.com/document/d/1nzgKw7JQ_fYuT9N0HCkz3gsu1lgDVIl2RwrhKlh2FS4/edit?usp=sharing)
- Social: would be nice to do some simple explainers for instagram
- Deadline: launch first thing in Jan so finish by Dec 20

### To dos for blog post
- [x] Meeting to brainstorm ideas for graphics with Kaili, Becca R, Natalie, Becca L
- [x] Designers to do some benchmarking and examples
- [x] Designers to sketch out concepts
- [x] Feedback on sketches
- [x] Natalie to determine art direction
- [x] Natalie to finalize graphics by Dec 20

### Phase 2 TBD
- More context [here](https://docs.google.com/document/d/1BU8Cfgd9o7euMRWN35ChQmJ74U9tcRZOxJCvR72F7bE/edit)
- Designers to shift back to this after [Venmo](https://github.com/MozillaFoundation/Design/issues/406)
- Brainstorm ideas for next steps

**Comment by kristinashu** [comment]
@natalieworth can you please link to the files you've already made on this topic?

**Comment by natalieworth** [comment]
Original Microtargeting story posts for [instagram are here](https://drive.google.com/drive/folders/1DqCEMUKXDrxX7cGc6eUPAa6w1l6zCRXV?usp=sharing).

**Comment by kristinashu** [comment]
Assigning to myself while I figure out what we and advocacy has in mind.

**Comment by kristinashu** [comment]
I'm going to start a running list of interesting related articles and resources around microtargeting, please add it:
- The Great Hack on Netfix gives an excellent overview in a simple way and will make you angry!
- Moco blog [post](https://blog.mozilla.org/internetcitizen/2018/10/04/microtargeting-dipayan-ghosh/) also gives a simplified overview
- Firefox shopping blog [post](https://blog.mozilla.org/firefox/holiday-shopping-privacy/) (thank you Tais for sharing)
- Weapons of Math Destruction mentions it and a lot of us read it during our book club
-
-

**Comment by kristinashu** [comment]
We had out kick-off today. Things are still fuzzy about if we should focus on political microtageting or general microtageting. But it seems like everyone agreed that some sort of tangible examples will be useful. Story arch _maybe_ start general and simple and then get more political. Key thing to keep in mind is that the post should be simple and we shouldn't try to do too much!

Next steps: Kaili and Becca R will jam together to work on copy. In the meantime, Natalie will work on some benchmarking and ideas as well. Nat, let Rebecca or I know if you want to chat or help with anything!

**Comment by natalieworth** [comment]
Update: Most recent [iterations are here in redpen](https://redpen.io/p/nxf2349abd7051af4e).

**Comment by natalieworth** [comment]
Still blocked/ awaiting some feedback from Sara, so going to leave this blocked until after the holidays:

**Working files are here for reference:**
[Illustrator file](https://drive.google.com/file/d/1X898UQjuFktBrPlnSAwZnzNKUFoQe23p/view?usp=sharing)
[Image treatment](https://drive.google.com/file/d/1OnSofH4PFIUDROtDXUcmQudhPMF1dI74/view?usp=sharing)
[Redpen](https://redpen.io/p/rba2a3369e6469d58c)

**Comment by natalieworth** [comment]
Update: Pinged Kaili and they are still waiting on approvals for the blog post, so more will come (in terms of visual feedback from team) once blog is approved.

**Comment by natalieworth** [comment]
Most recent 2 'final' treatments are in here https://redpen.io/p/rba2a3369e6469d58c

**Comment by alanmoo** [comment]
Still waiting for content approval

**Comment by natalieworth** [comment]
Final exports are here https://drive.google.com/drive/folders/12I53af5xUWnjMzF2B2HDkehEXDWVX-xT?usp=sharing

**Comment by natalieworth** [comment]
Closing this ticket and we can open a new tic if any additional sizes are needed for email, etc. :)
