### ISSUE TITLE
Build out UI in wmo.org/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#52]
- [x] Build Static Page (no external links) from #30 –  #56
- [x] Add External Links to Static Page with content from #32 – #57 
- [ ] Ensure metrics are in place from – #44 
- [ ] Design review
- [ ] Engineering review
- [ ] QA – https://github.com/MozillaFoundation/Design/issues/68
- [x] Ship to build.webmaker.org/design

**Comment by cassiemc** [comment]
@vazquez said he might be able to make progress on this next heartbeat.

**Comment by vazquez** [comment]
This issue has been triaged! :tractor:. 

I am optimistic about getting #56 done in time. I have doubts to get #57 done in time (not because of difficulty, but just time constraints)

**Comment by cassiemc** [comment]
I'm going to remove this from the milestone since you filed smaller tickets. Thanks @vazquez.

**Comment by vazquez** [comment]
@cassiemc - Can we close this issue since we have filed separate tickets?

**Comment by cassiemc** [comment]
Makes sense to me
