### ISSUE TITLE
[meta-ticket] Brand Position and Communications

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#524]
### Intro
Meta-ticket to track all brand position and communications collateral work.

### Issues
- [x] Meeting #497 [Apr 6 milestone]
- [x] Stakeholder Interview/Brief: Comms Collateral for Fundraising #520 [Apr 6 milestone]
- [ ] Comms Collateral: Document in /docs: #523
- [ ] Comms Collateral: Mozilla One-pager (print/digital): #522 
- [ ] Comms Collateral: MozFest One-pager (digital): #521

### Docs
Collateral list google doc: https://docs.google.com/document/d/1vu14K7tv9DA_vNkUqaz0Hg7WT4szvnsLcMx5EZdZw3E/edit?usp=sharing
Brand planning/meeting notes google doc: https://docs.google.com/document/d/1lJtLUbW3PRJ7kA8JWWRIgtIP_UTMYbrBwqlPBwNgU_U/edit?usp=sharing

cc: @kristinashu

**Comment by sabrinang** [comment]
Note: previous comms toolkit link that has lots of content from before that contains content we can move over to /docs comms to document on wagtail: https://mozilla.github.io/content/comms%20toolkit/

**Comment by kristinashu** [comment]
The idea of these one-pagers seems to have died, closing.
