### ISSUE TITLE
Epic: User Journey Map

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#553]
Follow up work from  #535

**Next Steps:**
- [ ] Send out feedback email to Anil, Jen and whoever else wants to be included
- [ ] Add in different types of channels (Owned, Earned, Paid)
- [ ] Think about how to get other teams to think about and understand the best channels for specific audience engagement
- [ ] Get audience empathy maps from Nat/Tais and flesh out the User Journey 
- [ ] Brand spreadsheet 
- [ ] _(Stretch Goal)_ Think more about practical applications and how we integrate this into our/staff's work flow (i.e. include more examples of how the spreadsheet could be used)

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
