### ISSUE TITLE
Epic: Concept Map

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#554]
Follow up work from #535

**Next Steps:**
- [ ] Gather feedback from staff on redpen (Engagement team?)
- [ ] Pick one diagrammatic and one story concept to refine
- [ ] Flesh out maps
- [ ] Get feedback

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
