### ISSUE TITLE
Define next steps for user journey work

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#555]
Follow up from: User Journey Phase 1: Functional UX system map and User journey map #535

### Todo
- [x] Prep for 5 min presentation (please don’t put too much extra work into this)
- [x] Send email for feedback (gather links and remind what type of feedback you’re looking for)
- [x] Add links to work week ticket #535 and close it
- [ ] Find ways to integrate this initial work into existing and upcoming work
- [x] Open new tickets with next steps
  - User Journey Map Next Steps #553
  - Concept Map Next Steps #554

**Comment by beccaklam** [comment]
@kristinashu Are our next steps tickets good to go or do we need to break them down further? I know you said we could just use them as meta/epic tickets, but wanted double check? cc: @sabrinang

**Comment by kristinashu** [comment]
Email to Anil for feedback has been sent!
