### ISSUE TITLE
Define next steps for audience work 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#556]
Follow up from: Create simple audience cards #545

### Todo
- [x] 1. Prep for 5 min presentation (please don’t put too much extra work into this)
- [x] 2. Send email for feedback (gather links and remind what type of feedback you’re looking for). 
- [x] 3. Add links to work week ticket #545 and close it
- [x] 4. Find ways to integrate this initial work into existing and upcoming work #560
- [x] 5. Open new tickets with next steps  #561

**Comment by natalieworth** [comment]
Draft for email is here https://docs.google.com/document/d/1T0u-ctn24H-qmKl8yy3lAtaP1V7nzZwRDap2ml6XOAM/edit

cc @kristinashu @taisdesouzalessa and tagging @sabrinang and @beccaklam if we want to send it together with the user journey work. :)

**Comment by natalieworth** [comment]
Dropping Taís' [next step notes here.](https://docs.google.com/document/d/104wGGx7Mp37bwTpukC0mw-QnoqCOVsTF5-NdkaHRRHM/edit)

[Email draft notes are here](https://docs.google.com/document/d/1T0u-ctn24H-qmKl8yy3lAtaP1V7nzZwRDap2ml6XOAM/edit)

**Comment by taisdesouzalessa** [comment]
Created GH tickets for items 4 and 5.

**Comment by taisdesouzalessa** [comment]
Shortened email. Send to Nat for feedback.

**Comment by natalieworth** [comment]
@taisdesouzalessa Thanks, [shortened copy](https://docs.google.com/document/d/1T0u-ctn24H-qmKl8yy3lAtaP1V7nzZwRDap2ml6XOAM/edit?usp=sharing) sounds good! I've sent to @kristinashu

**Comment by taisdesouzalessa** [comment]
Thanks @natalieworth! Closing this ticket since all tasks are done.
