### ISSUE TITLE
[Audience Work] Epic: Find ways to integrate Empathy Maps into existing and upcoming work

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#560]
**Potential projects to use the Empathy Maps**
- [ ] IA naming project

How can we quickly test them in the Content and Design Team’s work?
- [ ] Any new content the Content team writes targeting the novices and would-be activists sides of our audience
- [ ] Any new design assets the team creates targeting the novices and would-be activists sides of our audience

We will use the maps and encourage Content team to use them and well. We will report the results in this ticket.

cc: @natalieworth

**Comment by taisdesouzalessa** [comment]
Anil mentioned on his feedback that Xavier and Audrey are working on a “tech tips” project right now and suggested we get them to start road testing the maps and get their input on what’s helpful/what’s not. I contacted them and Xavier told he will use the maps and report back to us. 
**Note:** It may take a while to finish this project because they are still in the early stages.

**Comment by taisdesouzalessa** [comment]
This ticket is no longer relevant since audience issues are being raised in the Audience working group. The empathy maps were showed to the group as one of the artifacts we could use.
