### ISSUE TITLE
 [Audience work] Epic: Next steps

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#561]
### Next steps for Audience work:

**Short Term**
- [ ] Gather feedback from Anil and Content team
- [ ] Address feedback from them and refine Empathy Maps/presentation
- [ ] Develop a process for Content and Design collaboration on updating the map as we learn more about our audiences
_- [ ] Could we develop a proto-persona/ quick persona to test it’s usefulness with the empathy map?_ - in discussion between Taís and Nat. Not decided if we will do that or not.
- [ ] If gaps of knowledge are identified we should interview people from the groups we want to target and move from secondary research to primary research.
- [ ] Do a presentation for the Content team, focusing on the details of the maps, how to use them and how to evolve them + companion slide deck to them
- [ ] Measure results and iterate
- [ ] Think about how we can measure if we succeeded. 
- [ ] If practice is adopted by Content and Design team
- [ ] At the beginning, more informal conversations with the Content team will be enough to know how they feel about the map
- [ ] Later we can do a survey, once map is used enough times

**Future**
- [ ] Workshops (or any other method we consider useful) with other teams so they can have their empathy maps
- [ ] Consider evolving them into personas once we have more defined target audiences

cc: @natalieworth

**Comment by taisdesouzalessa** [comment]
Ticket not relevant anymore. We will be addressing audience in the 2021 Audience working group. Closing this ticket.
