### ISSUE TITLE
Banner design refresh

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#578]
We have been using our stylish black and white banner patterns for a while now. The abstract patterns work well because they are very responsive and the black/white design works with any content/images on the page. However, based on stakeholder interviews, there is a desire to show more people and faces on our site. Please explore different alternatives to our current banner graphics. Could be photos, could be photos but with a treatment, or could just be different abstract patterns. The outcome of this could be to stick with what we have, but we should at least be able to justify why.

### Todo
- [x] Brainstorm directions _(example: people photography/treatment, people illustrative, abstract patterns)_
- [x] Gather inspiration and create moodboards or example banners
- [ ] Get feedback on which direction

**Comment by sabrinang** [comment]
reduced this scope and filed issue to create banners here https://github.com/MozillaFoundation/Design/issues/583

**Comment by sabrinang** [comment]
banner brainstorm, moodboard, examples to be in WIP doc here: https://docs.google.com/presentation/d/1WD_tuur3adEz6WDLvhY3YJ4fyG2qK8vl0za4zMuBBv8/edit?usp=sharing

**Comment by sabrinang** [comment]
Scheduled to meet Nat and Becca tomorrow to review benchmarks, talk about the direction we want to take the banners in and catch up on any progress/iterations that have been made in the refresh or homepage designs to consider.

**Comment by sabrinang** [comment]
The direction we are going with is photography. 
- photography with full colour
- photography with a dark overlay or gradient for contrast
- can consider a backup option with subtle patterns but we want to make photography work so we are also revising the height of banners to accommodate this (will open separate issue addressing height)
