### ISSUE TITLE
Ring and Facial Recognition Campaign 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#582]
Advocacy will be running a campaign around ring and facial recognition. It would most likely need a graphic for email, social, and campaign page. We have already made graphics for Ring and also one around IA and facial recognition so we should try to reuse what we can.

[Advocacy brief doc.](https://docs.google.com/document/d/1sQjUwJC3uO9iLBpKUm7DupBUJ5mjWQStTzj3YlRcqxA/edit )

### Todos
- [ ] Meet with Kaili to be briefed
- [ ] Determine dimensions needed
- [ ] Create graphic direction and get feedback
- [ ] Once approved, scale graphic to different dimensions
