### ISSUE TITLE
Zoom e2ee graphic - due June 9

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#584]
Advocacy will be running a campaign targeting Zoom to provide end-to-end encryption. It would most likely need a graphic for email, social, and campaign page. We have already made graphics for Zoom and also ones around encryption so we should try to reuse what we can.

[Advocacy brief doc.](https://docs.google.com/document/d/1GFA-NgbQYmiI9jPTZcaxade17JoX-VC-mRU0ZkUlJP0/edit)

Email is supposed to go out June 10 so the graphic needs to be done June 9.

### Todos
- [x] Meet with Kaili for a quick briefed
- [x] Determine dimensions needed (might need to connect with Audrey for social)
- [x] Create graphic direction and get feedback
- [x] Once approved, scale graphic to different dimensions

**Comment by beccaklam** [comment]
Stakeholder brief with Kaili [here](https://docs.google.com/document/d/1Xx6PQ5XAggjhgRiINOKkK_Q3kdjnQeMI0YY5fpQ5srI/edit?usp=sharing)

[First draft in redpen here](https://redpen.io/p/edcc161463c4072536)

@kristinashu any thoughts?

**Comment by beccaklam** [comment]
Final assets [here](https://drive.google.com/drive/folders/1JSM9tv2Zw98h1v8nVmGvBtA8wE3NRqZb?usp=sharing) on the drive.
Working file [here](https://drive.google.com/file/d/1ZwU4UAg9Z3pwBW3YD1sIB0iHn0W_9cbR/view?usp=sharing) on the drive.

This should be done for now. Kaili said that Audrey currently doesn't need social assets. Kaili will also contact us again if she needs any new assets.
