### ISSUE TITLE
June fundraising photos

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#586]
Campaign plan is [here](https://docs.google.com/document/d/1ZxfSUH8ztiz-TT6sfn7jLtKWzgqYiCStIEdNPx-QD-E/edit).

### Deadline
June 17 email test

### Themes
- In these unsettled times of pandemic and racial injustice, the internet is more essential than ever -- for work, for entertainment, and for organizing social movements
- Mozilla is dedicated to putting YOU (not Big Tech corporations) in charge of your online life since 2003 -- and we’ll keep doing that.
- Mozilla is a nonprofit organization that depends on contributions from ordinary people like you to fund our work
- This end-of-H1 fundraising drive will help us raise funds for, and determine the scope of, our programs in the second half of 2020 - shaping up to be a crucial time for the free flow of information and protecting your privacy and security online.

### Todo
- [ ] 5-6 photo options of people (ideally faces) to test on landing pages
- [ ] ~Gather options to re-use old fundraising imagery~
- [ ] Determine dimensions (email, landing page)
- [ ] Get feedback from design team, Will, and Jen
- [ ] Crop selected graphics to fit

**Comment by beccaklam** [comment]
@kristinashu Selected some photos for the fundraising test [here](https://drive.google.com/open?id=14sA-T4qv_VDbKcB3pyl74juAQ8vJ1bpW).
More choices in this [folder as well](https://drive.google.com/drive/folders/1TwtZK8D1Mc50bOKpyKfeiLdp8lN63SDM?usp=sharing) (of people using tech).

**Comment by kristinashu** [comment]
Thanks Becca!

Here are a bunch of options https://docs.google.com/document/d/1pJdOB2nBi82zPR7Ey3aKUpMNcFmqgUxT7HeZbTjGgvE/edit. I'll share with design and stakeholders to +1 or -1. Once they've been narrowed down then I'll mock them up on the landing page and email.
