### ISSUE TITLE
[Epic] PNI marketing 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#682]
Contact person: Lindsay Dearlove

Brief from creative director: coming soon

Todos:
- [x] Design review for PNI marketing graphics #681
- [ ] Design review for PNI marketing video #680
- [x] Create GIFs for PNI marketing  #683 
- [x] OG images https://github.com/mozilla/foundation.mozilla.org/issues/4593
