### ISSUE TITLE
Graphics/Marketing style guide 2.0

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#724]
Document a process for working with agencies on design/social/marketing materials.

We can now link to as reference https://foundation.mozilla.org/en/docs/brand/agency-assets/ but it would be good to create a supplemental deck or framework where we provide contractors with context, what exists, direction or moodboard, audience or who we are reaching, desired applications, timeline etc. to be captured and handed off together

**Comment by kristinashu** [comment]
Nat, Sabs, and I had a great jam on this. Notes are [here](https://docs.google.com/document/d/1OLw5RGlHIXN1E8W40eg2iYD3AvNIUzB0UhS8jDCriTA/edit#heading=h.8l4itfumaszd). 

Steps to close this ticket
- [ ] Nat & Sabs to write an outline ToC for theme pages (Sabs: T.A.I MozFest / Nat: PNI)
- [ ] Nat & Sabs to open new tickets to build the pages
- [ ] Meet tomorrow to review together and decide on structure
- [ ] Kristina to open new additional tickets for other work that came out of the jam

**Comment by kristinashu** [comment]
@natalieworth @sabrinang could you please open those two tickets mentioned above and then this is good to close!

**Comment by kristinashu** [comment]
Thank you both! Closing (even though it's an epic because I don't think we need it open).
