### ISSUE TITLE
[Design ops] Guidelines for contractors/agencies

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#749]
Create a guide to share with staff and external design contractors/agencies.

### Notes
- Audience: staff hiring external design contractors/agencies as well as the people they hire (illustrators, videographers, animators, web designers)
- Purpose: clarify our process so we can manager expectation and streamline our onboarding process

### Related links
- Engagement team manifesto [(doc)](https://docs.google.com/document/d/1U2FUokl_9ZSZo6LOZrc9xBMt1LuHkitDvT7Zi3Dds4s/edit?ts=5fb553b3)
- Process for staff requesting design resources [(doc)](https://docs.google.com/document/d/1x34B6SPMUg1rMrzTaTaIw-ctgErluqQQ0LWE9kogKdQ/edit?ts=6009c858)
- How to work with us [(Wagtail)](https://foundation.mozilla.org/en/docs/process/work-with-us/)
- Brand guidelines [(Wagtail)](https://foundation.mozilla.org/en/docs/brand/)
- MozFest slide 40 [(Slides)](https://docs.google.com/presentation/d/1rtYVRyyZ4zKByCdpLzBL-F03oB2-r-dCNonAK78MPZI/edit#slide=id.g7f18615b03_0_6)

### Todo
- [x] Content outline
- [x] Determine url 
- [x] Build page
- [x] Consider how this fits in with other related content
- [ ] Open new tickets for additional work e.g. updating the Work With Us page
- [x] Consider opening a ticket for creating contractor spreadsheet
- [ ] Outline how to communicate this to staff

**Comment by kristinashu** [comment]
For context, I've started [this doc](https://docs.google.com/document/d/1SOI0xckmedNuf_5VH9Xwv508EGA1cXYtuYWQ2pqclIc/edit?usp=sharing) to start outlining and thinking about the bigger picture user flow for staff requesting work.

**Comment by sabrinang** [comment]
started a draft here: https://foundation.mozilla.org/en/docs/brand/process/collaboration/

**Comment by sabrinang** [comment]
contractor spreadsheet issue here: https://github.com/MozillaFoundation/Design/issues/766

**Comment by kristinashu** [comment]
@sabrinang what is left to do for this ticket? It seems done.

**Comment by sabrinang** [comment]
@kristinashu Looking at the to dos: 
- Do we need to open ticket to update work with us page? or communicating to staff?
- Do we need to build a page for bigger picture outline stuff?
I'm not entirely sure how to finish this ticket.

**Comment by kristinashu** [comment]
Ben is working on the new Work with us page in Mana and we (design) are aiming to share our design guideline at the staff call so I think this is good to close!
