### ISSUE TITLE
[Epic] Net Neutrality timeline & graphics

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#802]
Here is the [interview doc](https://docs.google.com/document/d/1lRP1jcxoXwDMdsCZgFlL1Vx9C0lqq8KpXL48ijGEf1s/edit#) which links to the Airtable requests from Kaili and Audrey. 

Nancy is responsible for doing the work but Natalie will support her in it (e.g. past work we've done on Net Neutrality as well as graphs, help with creative directions and dimensions/specs, help working with Kaili and Audrey, help staying on top of deadlines...). 

Here are some to-dos I can think of but please review them and open up individual tickets. 

- [x] Turn the interview into [a project brief](https://docs.google.com/document/d/1B9eJ5yEVRa_idaGFixcGG2ML-y3UmNT7brb0nlKCBZ0/edit?usp=sharing) (Nat)
- [x] Define creative direction (Nat) [#809](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/809)
- [x] Create graphs (Nancy) [#810](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/810)
- [x] Create Instagram graphics for timeline (Nancy) [#811](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/811)
- [x] Determine [URL and template type for MVP Wagtail page](https://foundation.mozilla.org/cms/pages/2015/edit/) (Nat)
- [x] Create graphics for MVP Wagtail page (Nancy but Nat can help out) [#813](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/813)
- [ ] Stretch: explore blue sky timeline template for Instagram and Website (Nat and Nancy if time) https://github.com/MozillaFoundation/Design/issues/822
- [ ] Stretch: Create a few gifs for social

### Links
[Copy doc from Audrey and Kaili is here](https://drive.google.com/file/d/1tWxK47OlRMUlHAvlveHyRdi-TIbcmss9/view) (but awaiting approval)
[Stat sheet for net neutrality graphics is here](https://docs.google.com/document/d/1uDqP0iQLuOnc3w594oaU1oBFTeqh_r8-NkuxYjQzeA8/edit)

**Comment by natalieworth** [comment]
March 30, 31

- [ ] Write brief
- [ ] Benchmark and establish creative direction

Nat
- Project brief (based on interview)
- Gather benchmarks for art direction
- Will finalize art direction by April 1

Nancy
- join Pinterest art direction [board here](https://pin.it/4u8n93d)
- Gather benchmarks for art direction

Shared between Nancy + Nat:
- Creative Direction
- Nat can also help with graphics/ production if needed

**Comment by natalieworth** [comment]
I've started on the [project brief here](https://docs.google.com/document/d/1B9eJ5yEVRa_idaGFixcGG2ML-y3UmNT7brb0nlKCBZ0/edit?usp=sharing) and left some questions for Audrey and Kaili to review.

**Comment by natalieworth** [comment]
URL will be under campaigns (e.g. campaigns/net-neutrality-timeline)

Wagtail [page is here](https://foundation.mozilla.org/cms/pages/2015/edit/)

**Comment by natalieworth** [comment]
Update:
Nancy has prepped everything for the IG timeline, wagtail timeline, and the 2 chart designs. We're awaiting copy approval and copy for the IG timeline—hoping approval will come on Monday/ next week.

**Comment by kristinashu** [comment]
Looks like MVP is done so I think this epic is good to close! Please reopen if needed.
