### ISSUE TITLE
TikTok paid political influence research

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#852]
Via Brandi [in Airtable](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recaIj1xoyAdlay8A?blocks=hide)

> We are trying to raise awareness of TikTok's problem with paid political content on the platform so that TikTok takes action on this and better regulations are developed around this issue at large.

> Deadline: May 19 but it's flexible by a few weeks. We need to publish this within this timeframe because we want it to kick off our work on monitoring TikTok ahead of the German election. 

Initial estimated scope:
- [x] Fill out out the [Design brief](https://docs.google.com/document/d/1fyAMb8Nhg-gf9rXSlkKYO0-Ak2So6AhGiUe0yjB57Qc/edit) with Brandi and Audrey
- [x] Propose a url (Becca is using /campaigns but we might move it to /research once that has been created)
- [x] Onboarding Brandi to the Publications template so she can add the content (Sabs #856)
- [x] Design review of publication  #855
- [x] Design review of PDF (Brandi/Becca to put into [doc template](https://docs.google.com/document/d/1R8tbiJpegXiC6PQMpWuTYPc-u1T8XDk2Qj_2aPxN4Xg/edit)) 
- [x] OG graphic: via Audrey "We won't be putting it on Instagram, but we'll be sharing it on twitter and linkedin, so it needs a good OG image. But that's really all that's required on social. I was thinking an OG image that was a stylised version ofTh€se Are Not Po£itical Ad$" (Nat #857) https://redpen.io/p/jd4653077bdd728cc8
- [x] I think Brandi wants some graphs but that might be out of scope (would require external contractor like P&G or Christian which will take time)

[Content doc.](https://docs.google.com/document/d/1pjag11Ny4RZbLsa2pBxJakD7UOMEDYRTo-a4oif2Yyk/edit#)

**Comment by jamilasnell** [comment]
Sabrina to help with onboarding Brandi onto the publications template.

**Comment by sabrinang** [comment]
I filed issues related to publications:
- [Publications] Onboarding Screenshare Video Walkthrough #856
- [Publications] Design review of TikTok paid political influence publication #855

**Comment by natalieworth** [comment]
Hey @sabrinang this is great! Yeah, I think my only thing is if it could be time-stamped in Youtube or even if it is on the foundation site somewhere, if it just has a legend that's like "Tables - 00:12:30."

**Comment by sabrinang** [comment]
Thanks for the feedback @natalieworth! Audrey replied she can help me get it uploaded some time today, I sent her a chapter outline too so I'm waiting for her response on that. If I can't get it on youtube I'll include the legend on the foundation site page. 

**Outline here:**
0:00-0:45 — Introduction
0:45-3:11 — How to create a Publication or Article Page
3:11-6:47 — General Page Features: Publication Page
6:47-8:29 — General Page Features: Child Publication Page
8:29-10:15 — Article Page Feature: Summary
10:15-10:57 — Content Block: Summary 
10:57-15:30 — Content Block: Images & Image Blocks
15:30-16:35 — Callout Block
16:35-23:15 — Tables & Advanced Table Blocks
23:15-26:00 — Footnotes Feature
26:00-26:33 — Previous/Next Buttons
26:33-27:30 — Social Buttons
27:30-28:10 — Content Transfer Tip
28:10-28:50 — Conclusion

**Comment by natalieworth** [comment]
The pdf looks good!

Still awaiting the 'published' version of the publication on Wagtail for final review (I'm not able to see TOC images unless it's officially published)—but hopefully going to be on June 3.
