### ISSUE TITLE
Graphics for Video Call Apps (due before Sept 21st)

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#908]
Lindsay is leading marketing for the call app edition. Other stakeholders: Anna for content, Audrey for social, Jen.

Would like to use Olly's fun cutout style.

Will need assets at different dimensions, work with Lindsay to confirm all dimensions (e.g. generic image for Call App category page, blog posts, press release. social media, email, etc). Could use the table from the [Graphics Request form](https://docs.google.com/document/d/1Q1VraPc5e9uTD6eR7C2WQZMyP1yxz77nBFtGdeyxBNM/edit#) to determine dimensions. 

#### Todo
- [ ] General Call App images (would be nice to have a few different options staff can pull from)
- [ ] Template App specific images so we can quickly and easily swap in different app logos 
- [ ] App specific image for key apps (work with Jen to figure out what they are) 

#### Links
- [Assets in Drive for 2021 Video Call logos](https://drive.google.com/drive/folders/1kEb_EGsttWT937zMOIkFEWr5RaR18yzJ?usp=sharing)
- [Assets in Drive from last years Video Call marketing](https://drive.google.com/drive/folders/14KyPsSCEZv39QfWBX-GT6RsmX-f3Rhtt?usp=sharing)
- [Olly's working files and template](https://drive.google.com/drive/folders/0B_rbDAen9prkS0N4MXRqaGo4bEE?resourcekey=0-30lbv7R8MPZVL_5U9uZ25Q)
- [Jen's Video Call App spreadsheet](https://docs.google.com/spreadsheets/d/1o_Yi7DoSMCb89U9o8OINJBp8H9zkX-f3kGdENekTnHY/edit#gid=1539013424)
- [Jen's WIP topline trends doc](https://docs.google.com/document/d/1qQW5J5ctN8O9xIxveHO7DobOdamW9haoMXJ6dOw7lXw/edit)
- [Meeting notes](https://docs.google.com/document/d/1MvQ441U1l1deKPY_iEunWlionyIke6JesBCEmWmW_D8/edit#heading=h.oms6m2jaejt2)

**Comment by nancyt1** [comment]
Filled out the lil [request form](https://docs.google.com/document/d/1WOXjxhgjAIap6hp1J3zAr_6JTCeSBePzH2JNsnacauo/edit#) with Lindsey with all the deliverables.

**Comment by kristinashu** [comment]
Notes in the request form look good!

**Comment by nancyt1** [comment]
[Redpen](https://redpen.io/p/zr7d6cc6ad1cb48691)
[Drive Folder](https://drive.google.com/drive/u/2/folders/12A_56kG14JMOz1lvQNUBjeiK8JAOLEYu)
Still working on assets for instagram since I got the [copy doc](https://docs.google.com/document/d/1o3JMHJxp2yuiw6OKnQPptOFSPAQHztA2fYjeZ7djQE8/edit) today.
