### ISSUE TITLE
Graphic for Slack campaign [due before Sept 21]

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#910]
Kaili is launching a campaign to tie-in to the release of the PNI video call project and need design assets. 

[Advocacy doc](https://docs.google.com/document/d/1ZLIGvd3biQ5B4sLZpy8uqUHlbQaLBqcPO3BbrEBwPMU/edit)

### Todo
- [x] Join campaign slack channel
- [x] Design to work with Kaili to fill out the [graphics request form](https://docs.google.com/document/d/1Q1VraPc5e9uTD6eR7C2WQZMyP1yxz77nBFtGdeyxBNM/edit#). I don't think all the fields are required but do need to determine the tone and mood for the graphic, brainstorm ideas, and determine deliverables (which sizes are needed and for what platforms).
- [x] Explore a few different directions and get feedback from stakeholders
- [x] Finalize design and export to all platforms

~Note that in later there might be an open letter associated with this and potentially a video.~ **Update**: Eugene will be making a video for this.

**Comment by nancyt1** [comment]
Filled out [request form ](https://docs.google.com/document/d/1pO49YeVvJxM-8y-se8HHKy0a-nS7tDY4BQS__lU_opg/edit#)with Kaili, going to sketch ideas next

**Comment by nancyt1** [comment]
Added my exports to the [drive](https://drive.google.com/drive/u/2/folders/122GoH-z6NzbpVASYjq-VlAc2gT9Q3k6l) and [redpen](https://redpen.io/p/xkbe6e6638b74c63be) for review.
