### ISSUE TITLE
[PNI Holiday Marketing] Epic

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#918]
Nov 9 soft-launch
Nov 16: full-launch

## Sprint 1
- [x] Nancy joining marketing brainstorm meeting [[Brainstorm Doc](https://docs.google.com/document/d/1OvFbGomWf_Rbu6ASWk93dFo_WCBGLIJSN4UZgxJHtCM/edit)]
- [x] Finalize [graphic request form](https://docs.google.com/document/d/1WIz7xEPOJHf0uQPkRfUkP14-lk_HKuAc2wpdRoWHfAc/edit?usp=sharing)
- [x] All designers [Pinning](https://www.pinterest.ca/mozillafoundationdesign/) & discuss during Jam time meeting
- [x] Creative ideation and exploration https://github.com/MozillaFoundation/Design/issues/923
- [x] Initial creation of graphic direction https://github.com/MozillaFoundation/Design/issues/924

## Sprint 2
- Solidify created graphic direction(s) mozillafoundation/design/issues/927
- Compile list of all necessary assets and their specs #931 
- Marketing production of assets mozillafoundation/design/issues/929

## Sprint 3
- Marketing production of assets [need ticket]
