### ISSUE TITLE
[Epic: PNI Holiday Marketing] Assets for blog posts and their promo

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#939]
Anna has hired writers to create several blog posts over the next couple of months.

The posts are outlined here:
https://docs.google.com/spreadsheets/d/1wWHHUrIj4dUzMmzyo88Bu5XKu4i0EtfreGhxwGkVQhg/edit#gid=1241253567

- [ ]  Blog Header Sizes
    - [ ]  1080 x 568
    - [ ]  1600 x 900
    - [ ]  1600 x 600

- [ ] We need to figure out the timing and order of posts
- [ ] Which posts need which assets
- [ ] Open tickets for each post and put it in appropriate sprint

[Redpen with explorations](https://redpen.io/p/oz7f6fb9fa8669035e)
[Drive where Anna keeps drafts](https://drive.google.com/drive/folders/1Jv0Qaeo5EVbjUySGThGWHkY59HLe0WBo)
Blog Post 1: https://github.com/MozillaFoundation/Design/issues/945
Blog Post 2: #951 
Blog Post 3: #957 
Blog Post 4: #969 
Blog Post 5: #959
