### ISSUE TITLE
[Epic] Blog Improvements on Foundation Site

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#960]
**Goal**
Improve the way we navigate, use, and find blog posts

**Proposed Steps**

- [x] Brief
- [x] Stakeholder interviews (Typeform survey to staff)
- [x] Landscape analysis
- [x] Design/prototype
- [ ] User testing
- [x] Design -> Dev handoff
- [ ] PR Reviews, Dev Collab

**Comment by kristinashu** [comment]
@nancyt1 do you want to close this? I think the bulk of the work is all done.
